workflows:
  android-workflow:
    name: Agenda Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.inchios.agendapadel"
      java: 17
    scripts:
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
      - name: Build Android App Bundle (Phone & Wear)
        script: |
          ./gradlew :app:bundleRelease :wear:bundleRelease --no-daemon
    artifacts:
      - app/build/outputs/bundle/release/*.aab
      - wear/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - inchiostro.stephane@hotmail.be
        notify:
          success: true
          failure: true

  ios-workflow:
    name: Agenda iOS Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        XCODE_WORKSPACE: "iosApp/iosApp.xcworkspace"
        XCODE_SCHEME: "iosApp"
      java: 17
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Setup Environment
        script: |
          JAVA_PATH=$(/usr/libexec/java_home -v 17)
          echo "JAVA_HOME=$JAVA_PATH" >> $CM_ENV
          echo "PATH=$JAVA_PATH/bin:$PATH" >> $CM_ENV
          sudo ln -sf $JAVA_PATH/bin/java /usr/local/bin/java
          java -version
      - name: Clean Environment
        script: |
          chmod +x gradlew
          ./gradlew clean --no-daemon
          rm -rf ~/.konan
          rm -rf shared/build
      - name: Generate Xcode Project
        script: |
          brew install xcodegen
          cd iosApp
          xcodegen generate
      - name: Install CocoaPods
        script: |
          chmod +x gradlew
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          export PATH=$JAVA_HOME/bin:$PATH
          
          # Génère le framework factice requis pour le podspec
          ./gradlew :shared:generateDummyFramework --no-daemon
          
          # Force la régénération du podspec
          ./gradlew :shared:podspec --no-daemon
          
          cd iosApp
          pod install
      - name: Build iOS App
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          export PATH=$JAVA_HOME/bin:$PATH
          
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            COMPILER_INDEX_STORE_ENABLE=NO
    artifacts:
      - iosApp/build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - inchiostro.stephane@hotmail.be
        notify:
          success: true
          failure: true
