platform :ios, '16.0'

target 'iosApp' do
  use_frameworks! :linkage => :static

  # On ne met QUE le module shared.
  # C'est lui qui tirera Firebase automatiquement via sa podspec.
  pod 'shared', :path => '../shared'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
  end
end
